name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configuração do Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Instalar dependências do Node.js
      - name: Install dependencies
        run: npm install

      # Rodar testes do Node.js
      - name: Run Node.js tests
        run: npm test

 
# 2. Login no Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ACESSO_DOCKER }}  # Configurado nos Secrets
          password: ${{ secrets.PASSAWORD }}  # Configurado nos Secrets

    # 3. Build da imagem Docker 
      - name: Build Docker image
        run: |
          docker build -t meu-usuario/nginx-exemplo:latest .

    # 4. Teste básico da imagem
      - name: Test Docker image
        run: |
          docker run -d --name nginx-test -p 8080:80 meu-usuario/nginx-exemplo:latest
          sleep 5  # Aguarda o contêiner inicializar
          curl -f http://localhost:8080  # Testa a página padrão do NGINX
          docker stop nginx-test && docker rm nginx-test  # Para e remove o contêiner

    # 5. Push da imagem para o Docker Hub
      - name: Push Docker image
        run: |
          docker push meu-usuario/nginx-exemplo:latest
